# Generated by Django 4.2.5 on 2023-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
